site_name: DIY Clone Hero Controller
repo_url: https://github.com/joshuaua/3Dprinted-CloneHero-Controller
docs_dir: ./Documentation
theme:
  name: material
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
nav:
    - Home: index.md
    - Supplies: supplies.md
    - "Build Guides":
        - "Simple Les Paul": simple-les-paul.md
